const PrivacyPolicy = () => {
  const content = [
    {
      heading: "1. INTRODUCTION",
      description: `WELCOME TO INDIAN DROPSHIPPING (“US,” “WE,” OR “OUR”). WE ARE COMMITTED TO PROTECTING YOUR PERSONAL INFORMATION AND YOUR RIGHT TO PRIVACY. THIS PRIVACY POLICY OUTLINES OUR PRACTICES REGARDING THE COLLECTION, USE, AND SHARING OF YOUR PERSONAL INFORMATION WHEN YOU USE OUR SERVICES.
      PLEASE TAKE A MOMENT TO CAREFULLY READ THIS PRIVACY POLICY TO UNDERSTAND HOW WE COLLECT, USE, AND SHARE YOUR PERSONAL INFORMATION. BY ACCESSING OR USING OUR SERVICES, YOU AGREE TO THE TERMS OF THIS PRIVACY POLICY.`,
    },
    {
      heading: "2. INFORMATION WE COLLECT",
      description: `WE MAY COLLECT PERSONAL INFORMATION THAT YOU PROVIDE DIRECTLY TO US WHEN YOU USE OUR SERVICES. THIS MAY INCLUDE:
      – CONTACT INFORMATION (SUCH AS YOUR NAME, EMAIL ADDRESS, PHONE NUMBER, AND PHYSICAL ADDRESS)
      – PAYMENT INFORMATION (SUCH AS CREDIT CARD DETAILS)
      – INFORMATION YOU PROVIDE WHEN YOU CONTACT OUR CUSTOMER SUPPORT
      – INFORMATION YOU PROVIDE WHEN YOU PARTICIPATE IN SURVEYS OR PROMOTIONS
      ADDITIONALLY, WE MAY AUTOMATICALLY COLLECT CERTAIN INFORMATION WHEN YOU USE OUR SERVICES, SUCH AS:
      – LOG INFORMATION (INCLUDING YOUR IP ADDRESS, BROWSER TYPE, AND OPERATING SYSTEM)
      – USAGE INFORMATION (SUCH AS PAGES YOU VISIT AND ACTIONS YOU TAKE ON OUR PLATFORM)`,
    },
    {
      heading: "3. HOW WE USE YOUR INFORMATION",
      description: `WE MAY USE THE INFORMATION WE COLLECT FOR VARIOUS PURPOSES, INCLUDING:
      – PROVIDING AND IMPROVING OUR SERVICES
      – PROCESSING TRANSACTIONS AND SENDING TRANSACTION NOTIFICATIONS
      – COMMUNICATING WITH YOU ABOUT OUR SERVICES, PROMOTIONS, AND UPDATES
      – RESPONDING TO YOUR INQUIRIES AND PROVIDING CUSTOMER SUPPORT
      – CONDUCTING RESEARCH AND ANALYSIS TO IMPROVE OUR SERVICES`,
    },
    {
      heading: "4. INFORMATION SHARING",
      description: `WE MAY SHARE YOUR PERSONAL INFORMATION WITH THIRD PARTIES IN THE FOLLOWING CIRCUMSTANCES:
      – WITH YOUR CONSENT
      – WITH SERVICE PROVIDERS WHO HELP US DELIVER OUR SERVICES
      – TO COMPLY WITH LEGAL OBLIGATIONS OR TO PROTECT OUR RIGHTS
      – IN CONNECTION WITH A MERGER, ACQUISITION, OR SALE OF ALL OR A PORTION OF OUR BUSINESS`,
    },
    {
      heading: "5. YOUR CHOICES",
      description: `YOU HAVE THE RIGHT TO:
      – ACCESS AND UPDATE YOUR PERSONAL INFORMATION
      – OPT-OUT OF RECEIVING PROMOTIONAL COMMUNICATIONS
      – DELETE YOUR ACCOUNT AND PERSONAL INFORMATION`,
    },
    {
      heading: "6. SECURITY",
      description: `WE TAKE REASONABLE MEASURES TO PROTECT YOUR PERSONAL INFORMATION FROM UNAUTHORIZED ACCESS, DISCLOSURE, OR ALTERATION. HOWEVER, NO DATA TRANSMISSION OVER THE INTERNET CAN BE GUARANTEED AS 100% SECURE. YOU ARE RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR ACCOUNT INFORMATION.`,
    },
    {
      heading: "7. CHILDREN’S PRIVACY",
      description: `OUR SERVICES ARE NOT INTENDED FOR CHILDREN UNDER THE AGE OF 13. WE DO NOT KNOWINGLY COLLECT OR SOLICIT PERSONAL INFORMATION FROM CHILDREN. IF YOU BELIEVE THAT WE MIGHT HAVE COLLECTED PERSONAL INFORMATION FROM A CHILD, PLEASE CONTACT US.`,
    },
    {
      heading: "8. CHANGES TO THIS PRIVACY POLICY",
      description: `WE MAY UPDATE THIS PRIVACY POLICY FROM TIME TO TIME. ANY CHANGES WILL BE EFFECTIVE WHEN WE POST THE UPDATED PRIVACY POLICY ON OUR WEBSITE.`,
    },
    {
      heading: "9. CONTACT US",
      description: `IF YOU HAVE ANY QUESTIONS, CONCERNS, OR REQUESTS REGARDING THIS PRIVACY POLICY, PLEASE CONTACT US AT ALAGAN@DELTARTSTORE.SHOP.
      BY USING OUR SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTOOD THIS PRIVACY POLICY.`,
    },
  ];

  return (
    <>
      <div className="text-white flex flex-col items-center justify-center p-2 md:px-20">
        <h1 className="text-2xl md:text-4xl font-bold">PRIVACY POLICY</h1>
        <ul>
          {content.map((content, index) => (
            <li key={index} className="p-2">
              <h1 className="text-xl md:text-2xl font-bold p-2">
                {content.heading}
              </h1>

              <p className="text-md md:text-lg px-6">{content.description}</p>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
};

export default PrivacyPolicy;
