const TermsAndCondition = () => {
  return (
    <div className="text-white flex flex-col items-center justify-center p-2 md:px-20">
      <h1 className="text-2xl md:text-4xl font-bold">TERMS AND CONDITIONS</h1>
      <p className="text-md md:text-lg p-3 text-center w-full">
        GENERAL THIS WEBSITE (THE “SITE”) IS OWNED AND OPERATED BY TAMILALAGAN
        D/B/A “DELTART” (“COMPANY,” “WE” OR “US”). BY USING THE SITE, YOU AGREE
        TO BE BOUND BY THESE TERMS OF SERVICE AND TO USE THE SITE IN ACCORDANCE
        WITH THESE TERMS OF SERVICE, OUR PRIVACY POLICY, AND ANY ADDITIONAL
        TERMS AND CONDITIONS THAT MAY APPLY TO SPECIFIC SECTIONS OF THE SITE OR
        TO PRODUCTS AND SERVICES AVAILABLE THROUGH THE SITE OR FROM COMPANY.
        ACCESSING THE SITE, IN ANY MANNER, WHETHER AUTOMATED OR OTHERWISE,
        CONSTITUTES USE OF THE SITE AND YOUR AGREEMENT TO BE BOUND BY THESE
        TERMS OF SERVICE. WE RESERVE THE RIGHT TO CHANGE THESE TERMS OF SERVICE
        OR TO IMPOSE NEW CONDITIONS ON USE OF THE SITE, FROM TIME TO TIME, IN
        WHICH CASE WE WILL POST THE REVISED TERMS OF SERVICE ON THIS WEBSITE. BY
        CONTINUING TO USE THE SITE AFTER WE POST ANY SUCH CHANGES, YOU ACCEPT
        THE TERMS OF SERVICE, AS MODIFIED.
        <br />
        <br />
        INTELLECTUAL PROPERTY RIGHTS. OUR LIMITED LICENSE TO YOU THIS SITE AND
        ALL THE MATERIALS AVAILABLE ON THE SITE ARE THE PROPERTY OF US AND/OR
        OUR AFFILIATES OR LICENSORS, AND ARE PROTECTED BY COPYRIGHT, TRADEMARK,
        AND OTHER INTELLECTUAL PROPERTY LAWS. THE SITE IS PROVIDED SOLELY FOR
        YOUR PERSONAL NONCOMMERCIAL USE. YOU MAY NOT USE THE SITE OR THE
        MATERIALS AVAILABLE ON THE SITE IN A MANNER THAT CONSTITUTES AN
        INFRINGEMENT OF OUR RIGHTS OR THAT HAS NOT BEEN AUTHORIZED BY US. MORE
        SPECIFICALLY, UNLESS EXPLICITLY AUTHORIZED IN THESE TERMS OF SERVICE OR
        BY THE OWNER OF THE MATERIALS, YOU MAY NOT MODIFY, COPY, REPRODUCE,
        REPUBLISH, UPLOAD, POST, TRANSMIT, TRANSLATE, SELL, CREATE DERIVATIVE
        WORKS, EXPLOIT, OR DISTRIBUTE IN ANY MANNER OR MEDIUM (INCLUDING BY
        EMAIL OR OTHER ELECTRONIC MEANS) ANY MATERIAL FROM THE SITE. YOU MAY,
        HOWEVER, FROM TIME TO TIME, DOWNLOAD AND/OR PRINT ONE COPY OF INDIVIDUAL
        PAGES OF THE SITE FOR YOUR PERSONAL, NON-COMMERCIAL USE, PROVIDED THAT
        YOU KEEP INTACT ALL COPYRIGHT AND OTHER PROPRIETARY NOTICES.
        <br />
        <br />
        YOUR LICENSE TO US BY POSTING OR SUBMITTING ANY MATERIAL (INCLUDING,
        WITHOUT LIMITATION, COMMENTS, BLOG ENTRIES, FACEBOOK POSTINGS, PHOTOS,
        AND VIDEOS) TO US VIA THE SITE, INTERNET GROUPS, SOCIAL MEDIA VENUES, OR
        TO ANY OF OUR STAFF VIA EMAIL, TEXT, OR OTHERWISE, YOU ARE REPRESENTING:
        (I) THAT YOU ARE THE OWNER OF THE MATERIAL, OR ARE MAKING YOUR POSTING
        OR SUBMISSION WITH THE EXPRESS CONSENT OF THE OWNER OF THE MATERIAL; AND
        (II) THAT YOU ARE THIRTEEN YEARS OF AGE OR OLDER. IN ADDITION, WHEN YOU
        SUBMIT, EMAIL, TEXT OR DELIVER OR POST ANY MATERIAL, YOU ARE GRANTING
        US, AND ANYONE AUTHORIZED BY US, A ROYALTY-FREE, PERPETUAL, IRREVOCABLE,
        NON-EXCLUSIVE, UNRESTRICTED, WORLDWIDE LICENSE TO USE, COPY, MODIFY,
        TRANSMIT, SELL, EXPLOIT, CREATE DERIVATIVE WORKS FROM, DISTRIBUTE,
        AND/OR PUBLICLY PERFORM OR DISPLAY SUCH MATERIAL, IN WHOLE OR IN PART,
        IN ANY MANNER OR MEDIUM, NOW KNOWN OR HEREAFTER DEVELOPED, FOR ANY
        PURPOSE. THE FOREGOING GRANT SHALL INCLUDE THE RIGHT TO EXPLOIT ANY
        PROPRIETARY RIGHTS IN SUCH POSTING OR SUBMISSION, INCLUDING, BUT NOT
        LIMITED TO, RIGHTS UNDER COPYRIGHT, TRADEMARK, SERVICE MARK, OR PATENT
        LAWS UNDER ANY RELEVANT JURISDICTION. ALSO, IN CONNECTION WITH THE
        EXERCISE OF SUCH RIGHTS, YOU GRANT US, AND ANYONE AUTHORIZED BY US, THE
        RIGHT TO IDENTIFY YOU AS THE AUTHOR OF ANY OF YOUR POSTINGS OR
        SUBMISSIONS BY NAME, EMAIL ADDRESS OR SCREEN NAME, AS WE DEEM
        APPROPRIATE.
        <br />
        <br />
        YOU ACKNOWLEDGE AND AGREE THAT ANY CONTRIBUTIONS ORIGINALLY CREATED BY
        YOU FOR US SHALL BE DEEMED A “WORK MADE FOR HIRE” WHEN THE WORK
        PERFORMED IS WITHIN THE SCOPE OF THE DEFINITION OF A WORK MADE FOR HIRE
        IN SECTION 101 OF THE UNITED STATES COPYRIGHT LAW, AS AMENDED. AS SUCH,
        THE COPYRIGHTS IN THOSE WORKS SHALL BELONG TO COMPANY FROM THEIR
        CREATION. THUS, COMPANY SHALL BE DEEMED THE AUTHOR AND EXCLUSIVE OWNER
        THEREOF AND SHALL HAVE THE RIGHT TO EXPLOIT ANY OR ALL OF THE RESULTS
        AND PROCEEDS IN ANY AND ALL MEDIA, NOW KNOWN OR HEREAFTER DEVISED,
        THROUGHOUT THE UNIVERSE, IN PERPETUITY, IN ALL LANGUAGES, AS COMPANY
        DETERMINES. IN THE EVENT THAT ANY OF THE RESULTS AND PROCEEDS OF YOUR
        SUBMISSIONS HEREUNDER ARE NOT DEEMED A “WORK MADE FOR HIRE” UNDER
        SECTION 101 OF THE COPYRIGHT ACT, AS AMENDED, YOU HEREBY, WITHOUT
        ADDITIONAL COMPENSATION, IRREVOCABLY ASSIGN, CONVEY AND TRANSFER TO
        COMPANY ALL PROPRIETARY RIGHTS, INCLUDING WITHOUT LIMITATION, ALL
        COPYRIGHTS, AND TRADEMARKS THROUGHOUT THE UNIVERSE, IN PERPETUITY IN
        EVERY MEDIUM, WHETHER NOW KNOWN OR HEREAFTER DEVISED, TO SUCH MATERIAL
        AND ANY AND ALL RIGHT, TITLE AND INTEREST IN AND TO ALL SUCH PROPRIETARY
        RIGHTS IN EVERY MEDIUM, WHETHER NOW KNOWN OR HEREAFTER DEVISED,
        THROUGHOUT THE UNIVERSE, IN PERPETUITY. ANY POSTED MATERIAL WHICH ARE
        REPRODUCTIONS OF PRIOR WORKS BY YOU SHALL BE CO-OWNED BY US.
        <br />
        <br />
        YOU ACKNOWLEDGE THAT COMPANY HAS THE RIGHT BUT NOT THE OBLIGATION TO USE
        AND DISPLAY ANY POSTINGS OR CONTRIBUTIONS OF ANY KIND AND THAT COMPANY
        MAY ELECT TO CEASE THE USE AND DISPLAY OF ANY SUCH MATERIALS (OR ANY
        PORTION THEREOF), AT ANY TIME FOR ANY REASON WHATSOEVER.
        <br />
        <br />
        LIMITATIONS ON LINKING AND FRAMING. YOU MAY ESTABLISH A HYPERTEXT LINK
        TO THE SITE SO LONG AS THE LINK DOES NOT STATE OR IMPLY ANY SPONSORSHIP
        OF YOUR SITE BY US OR BY THE SITE. HOWEVER, YOU MAY NOT, WITHOUT OUR
        PRIOR WRITTEN PERMISSION, FRAME OR INLINE LINK ANY OF THE CONTENT OF THE
        SITE, OR INCORPORATE INTO ANOTHER WEBSITE OR OTHER SERVICE ANY OF OUR
        MATERIAL, CONTENT, OR INTELLECTUAL PROPERTY.
        <br />
        <br />
        DISCLAIMERS THROUGHOUT THE SITE, WE MAY PROVIDE LINKS AND POINTERS TO
        INTERNET SITES MAINTAINED BY THIRD PARTIES. OUR LINKING TO SUCH
        THIRD-PARTY SITES DOES NOT IMPLY AN ENDORSEMENT OR SPONSORSHIP OF SUCH
        SITES OR THE INFORMATION, PRODUCTS, OR SERVICES OFFERED ON OR THROUGH
        THE SITES. IN ADDITION, NEITHER WE NOR AFFILIATES OPERATE OR CONTROL IN
        ANY RESPECT ANY INFORMATION, PRODUCTS, OR SERVICES THAT THIRD PARTIES
        MAY PROVIDE ON OR THROUGH THE SITE OR ON WEBSITES LINKED TO BY US ON THE
        SITE. IF APPLICABLE, ANY OPINIONS, ADVICE, STATEMENTS, SERVICES, OFFERS,
        OR OTHER INFORMATION OR CONTENT EXPRESSED OR MADE AVAILABLE BY THIRD
        PARTIES, INCLUDING INFORMATION PROVIDERS, ARE THOSE OF THE RESPECTIVE
        AUTHORS OR DISTRIBUTORS, AND NOT COMPANY. NEITHER COMPANY NOR ANY
        THIRD-PARTY PROVIDER OF INFORMATION GUARANTEES THE ACCURACY,
        COMPLETENESS, OR USEFULNESS OF ANY CONTENT. FURTHERMORE, COMPANY NEITHER
        ENDORSES NOR IS RESPONSIBLE FOR THE ACCURACY AND RELIABILITY OF ANY
        OPINION, ADVICE, OR STATEMENT MADE ON ANY OF THE SITES BY ANYONE OTHER
        THAN AN AUTHORIZED COMPANY REPRESENTATIVE WHILE ACTING IN HIS/HER
        OFFICIAL CAPACITY.
        <br />
        <br />
        THE INFORMATION, PRODUCTS, AND SERVICES OFFERED ON OR THROUGH THE SITE
        AND BY THE COMPANY AND ANY THIRD-PARTY SITES ARE PROVIDED “AS IS” AND
        WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST
        EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE DISCLAIM ALL
        WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED
        WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. WE
        DO NOT WARRANT THAT THE SITE OR ANY OF ITS FUNCTIONS WILL BE
        UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT ANY
        PART OF THIS SITE, INCLUDING BULLETIN BOARDS, OR THE SERVERS THAT MAKE
        IT AVAILABLE, ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE DO NOT
        WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF
        THE USE OF THE SITE OR MATERIALS ON THIS SITE OR ON THIRD-PARTY SITES IN
        TERMS OF THEIR CORRECTNESS, ACCURACY, TIMELINESS, RELIABILITY, OR
        OTHERWISE. YOU AGREE AT ALL TIMES TO DEFEND, INDEMNIFY, AND HOLD
        HARMLESS COMPANY ITS AFFILIATES, THEIR SUCCESSORS, TRANSFEREES, ASSIGNS
        AND LICENSEES AND THEIR RESPECTIVE PARENT AND SUBSIDIARY COMPANIES,
        AGENTS, ASSOCIATES, OFFICERS, DIRECTORS, SHAREHOLDERS, AND EMPLOYEES OF
        EACH FROM AND AGAINST ANY AND ALL CLAIMS, CAUSES OF ACTION, DAMAGES,
        LIABILITIES, COSTS AND EXPENSES, INCLUDING LEGAL FEES AND EXPENSES,
        ARISING OUT OF OR RELATED TO YOUR BREACH OF ANY OBLIGATION, WARRANTY,
        REPRESENTATION, OR COVENANT SET FORTH HEREIN.
        <br />
        <br />
        ONLINE COMMERCE CERTAIN SECTIONS OF THE SITE MAY ALLOW YOU TO PURCHASE
        MANY DIFFERENT TYPES OF PRODUCTS AND SERVICES ONLINE THAT ARE PROVIDED
        BY THIRD PARTIES. WE ARE NOT RESPONSIBLE FOR THE QUALITY, ACCURACY,
        TIMELINESS, RELIABILITY, OR ANY OTHER ASPECT OF THESE PRODUCTS AND
        SERVICES. IF YOU MAKE A PURCHASE FROM A MERCHANT ON THE SITE OR ON A
        SITE LINKED TO BY THE SITE, THE INFORMATION OBTAINED DURING YOUR VISIT
        TO THAT MERCHANT’S ONLINE STORE OR SITE, AND THE INFORMATION THAT YOU
        GIVE AS PART OF THE TRANSACTION, SUCH AS YOUR CREDIT CARD NUMBER AND
        CONTACT INFORMATION, MAY BE COLLECTED BY BOTH THE MERCHANT AND US. A
        MERCHANT MAY HAVE PRIVACY AND DATA COLLECTION PRACTICES THAT ARE
        DIFFERENT FROM OURS. WE HAVE NO RESPONSIBILITY OR LIABILITY FOR THESE
        INDEPENDENT POLICIES. IN ADDITION, WHEN YOU PURCHASE PRODUCTS OR
        SERVICES ON OR THROUGH THE SITE, YOU MAY BE SUBJECT TO ADDITIONAL TERMS
        AND CONDITIONS THAT SPECIFICALLY APPLY TO YOUR PURCHASE OR USE OF SUCH
        PRODUCTS OR SERVICES. FOR MORE INFORMATION REGARDING A MERCHANT, ITS
        ONLINE STORE, ITS PRIVACY POLICIES, AND/OR ANY ADDITIONAL TERMS AND
        CONDITIONS THAT MAY APPLY, VISIT THAT MERCHANT’S WEBSITE AND CLICK ON
        ITS INFORMATION LINKS OR CONTACT THE MERCHANT DIRECTLY. YOU RELEASE US
        AND OUR AFFILIATES FROM ANY DAMAGES THAT YOU INCUR, AND AGREE NOT TO
        ASSERT ANY CLAIMS AGAINST US OR THEM, ARISING FROM YOUR PURCHASE OR USE
        OF ANY PRODUCTS OR SERVICES MADE AVAILABLE BY THIRD PARTIES THROUGH THE
        SITE.
        <br />
        <br />
        YOUR PARTICIPATION, CORRESPONDENCE OR BUSINESS DEALINGS WITH ANY THIRD
        PARTY FOUND ON OR THROUGH OUR SITE, REGARDING PAYMENT AND DELIVERY OF
        SPECIFIC GOODS AND SERVICES, AND ANY OTHER TERMS, CONDITIONS,
        REPRESENTATIONS OR WARRANTIES ASSOCIATED WITH SUCH DEALINGS, ARE SOLELY
        BETWEEN YOU AND SUCH THIRD PARTY. YOU AGREE THAT COMPANY SHALL NOT BE
        RESPONSIBLE OR LIABLE FOR ANY LOSS, DAMAGE, OR OTHER MATTERS OF ANY SORT
        INCURRED AS THE RESULT OF ANY SUCH DEALINGS.
        <br />
        <br />
        YOU AGREE TO BE FINANCIALLY RESPONSIBLE FOR ALL PURCHASES MADE BY YOU OR
        SOMEONE ACTING ON YOUR BEHALF THROUGH THE SITE. YOU AGREE TO USE THE
        SITE AND TO PURCHASE SERVICES OR PRODUCTS THROUGH THE SITE FOR
        LEGITIMATE, NON-COMMERCIAL PURPOSES ONLY. YOU ALSO AGREE NOT TO MAKE ANY
        PURCHASES FOR SPECULATIVE, FALSE, OR FRAUDULENT PURPOSES OR FOR THE
        PURPOSE OF ANTICIPATING DEMAND FOR A PARTICULAR PRODUCT OR SERVICE. YOU
        AGREE TO ONLY PURCHASE GOODS OR SERVICES FOR YOURSELF OR FOR ANOTHER
        PERSON FOR WHOM YOU ARE LEGALLY PERMITTED TO DO SO. WHEN MAKING A
        PURCHASE FOR A THIRD PARTY THAT REQUIRES YOU TO SUBMIT THE THIRD PARTY’S
        PERSONAL INFORMATION TO US OR A MERCHANT, YOU REPRESENT THAT YOU HAVE
        OBTAINED THE EXPRESS CONSENT OF SUCH THIRD PARTY TO PROVIDE SUCH THIRD
        PARTY’S PERSONAL INFORMATION.
        <br />
        <br />
        INTERACTIVE FEATURES THIS SITE MAY INCLUDE A VARIETY OF FEATURES, SUCH
        AS BULLETIN BOARDS, WEBLOGS, CHAT ROOMS, AND EMAIL SERVICES, WHICH ALLOW
        FEEDBACK TO US AND REAL-TIME INTERACTION BETWEEN USERS, AND OTHER
        FEATURES WHICH ALLOW USERS TO COMMUNICATE WITH OTHERS. RESPONSIBILITY
        FOR WHAT IS POSTED ON BULLETIN BOARDS, WEBLOGS, CHAT ROOMS, AND OTHER
        PUBLIC POSTING AREAS ON THE SITE, OR SENT VIA ANY EMAIL SERVICES ON THE
        SITE, LIES WITH EACH USER – YOU ALONE ARE RESPONSIBLE FOR THE MATERIAL
        YOU POST OR SEND. WE DO NOT CONTROL THE MESSAGES, INFORMATION, OR FILES
        THAT YOU OR OTHERS MAY PROVIDE THROUGH THE SITE. IT IS A CONDITION OF
        YOUR USE OF THE SITE THAT YOU DO NOT:
        <br />
        <br />
        – RESTRICT OR INHIBIT ANY OTHER USER FROM USING AND ENJOYING THE SITE.
        <br />
        <br />
        – USE THE SITE TO IMPERSONATE ANY PERSON OR ENTITY, OR FALSELY STATE OR
        OTHERWISE MISREPRESENT YOUR AFFILIATION WITH A PERSON OR ENTITY.
        <br />
        <br />
        – INTERFERE WITH OR DISRUPT ANY SERVERS OR NETWORKS USED TO PROVIDE THE
        SITE OR ITS FEATURES, OR DISOBEY ANY REQUIREMENTS, PROCEDURES, POLICIES,
        OR REGULATIONS OF THE NETWORKS WE USE TO PROVIDE THE SITE.
        <br />
        <br />
        – USE THE SITE TO INSTIGATE OR ENCOURAGE OTHERS TO COMMIT ILLEGAL
        ACTIVITIES OR CAUSE INJURY OR PROPERTY DAMAGE TO ANY PERSON.
        <br />
        <br />
        – GAIN UNAUTHORIZED ACCESS TO THE SITE, OR ANY ACCOUNT, COMPUTER SYSTEM,
        OR NETWORK CONNECTED TO THIS SITE, BY MEANS SUCH AS HACKING, PASSWORD
        MINING, OR OTHER ILLICIT MEANS.
        <br />
        <br />
        – OBTAIN OR ATTEMPT TO OBTAIN ANY MATERIALS OR INFORMATION THROUGH ANY
        MEANS NOT INTENTIONALLY MADE AVAILABLE THROUGH THIS SITE.
        <br />
        <br />
        – USE THE SITE TO POST OR TRANSMIT ANY UNLAWFUL, THREATENING, ABUSIVE,
        LIBELOUS, DEFAMATORY, OBSCENE, VULGAR, PORNOGRAPHIC, PROFANE, OR
        INDECENT INFORMATION OF ANY KIND, INCLUDING WITHOUT LIMITATION ANY
        TRANSMISSIONS CONSTITUTING OR ENCOURAGING CONDUCT THAT WOULD CONSTITUTE
        A CRIMINAL OFFENSE, GIVE RISE TO CIVIL LIABILITY, OR OTHERWISE VIOLATE
        ANY LOCAL, STATE, NATIONAL, OR INTERNATIONAL LAW.
        <br />
        <br />
        – USE THE SITE TO POST OR TRANSMIT ANY INFORMATION, SOFTWARE, OR OTHER
        MATERIAL THAT VIOLATES OR INFRINGES UPON THE RIGHTS OF OTHERS, INCLUDING
        MATERIAL THAT IS AN INVASION OF PRIVACY OR PUBLICITY RIGHTS OR THAT IS
        PROTECTED BY COPYRIGHT, TRADEMARK, OR OTHER PROPRIETARY RIGHT, OR
        DERIVATIVE WORKS WITH RESPECT THERETO, WITHOUT FIRST OBTAINING
        PERMISSION FROM THE OWNER OR RIGHTHOLDER.
        <br />
        <br />
        – USE THE SITE TO POST OR TRANSMIT ANY INFORMATION, SOFTWARE, OR OTHER
        MATERIAL THAT CONTAINS A VIRUS OR OTHER HARMFUL COMPONENT.
        <br />
        <br />
        – USE THE SITE TO POST, TRANSMIT OR IN ANY WAY EXPLOIT ANY INFORMATION,
        SOFTWARE, OR OTHER MATERIAL FOR COMMERCIAL PURPOSES, OR THAT CONTAINS
        ADVERTISING.
        <br />
        <br />
        – USE THE SITE TO ADVERTISE OR SOLICIT TO ANYONE TO BUY OR SELL PRODUCTS
        OR SERVICES, OR TO MAKE DONATIONS OF ANY KIND, WITHOUT OUR EXPRESS
        WRITTEN APPROVAL.
        <br />
        <br />
        – GATHER FOR MARKETING PURPOSES ANY EMAIL ADDRESSES OR OTHER PERSONAL
        INFORMATION THAT HAS BEEN POSTED BY OTHER USERS OF THE SITE.
        <br />
        <br />
        COMPANY MAY HOST MESSAGE BOARDS, CHAT ROOMS, AND OTHER PUBLIC FORUMS ON
        ITS SITES. ANY USER FAILING TO COMPLY WITH THE TERMS AND CONDITIONS OF
        THIS AGREEMENT MAY BE EXPELLED FROM AND REFUSED CONTINUED ACCESS TO, THE
        MESSAGE BOARDS, CHAT ROOMS, OR OTHER PUBLIC FORUMS IN THE FUTURE.
        COMPANY OR ITS DESIGNATED AGENTS MAY REMOVE OR ALTER ANY USER-CREATED
        CONTENT AT ANY TIME FOR ANY REASON. MESSAGE BOARDS, CHAT ROOMS, AND
        OTHER PUBLIC FORUMS ARE INTENDED TO SERVE AS DISCUSSION CENTERS FOR
        USERS AND SUBSCRIBERS. INFORMATION AND CONTENT POSTED WITHIN THESE
        PUBLIC FORUMS MAY BE PROVIDED BY COMPANY STAFF, COMPANY’S OUTSIDE
        CONTRIBUTORS, OR BY USERS NOT CONNECTED WITH COMPANY, SOME OF WHOM MAY
        EMPLOY ANONYMOUS USER NAMES. COMPANY EXPRESSLY DISCLAIMS ALL
        RESPONSIBILITY AND ENDORSEMENT AND MAKES NO REPRESENTATION AS TO THE
        VALIDITY OF ANY OPINION, ADVICE, INFORMATION, OR STATEMENT MADE OR
        DISPLAYED IN THESE FORUMS BY THIRD PARTIES, NOR ARE WE RESPONSIBLE FOR
        ANY ERRORS OR OMISSIONS IN SUCH POSTINGS, OR FOR HYPERLINKS EMBEDDED IN
        ANY MESSAGES.
        <br />
        WE IN NO WAY ENDORSE OR GUARANTEE THE ACCURACY OF ANY POSTING REGARDLESS
        OF WHETHER THE POSTING COMES FROM A USER, FROM A CELEBRITY, OR “EXPERT”
        GUEST OR FROM A MEMBER OF OUR STAFF.
        <br />
        <br />
        NEITHER COMPANY NOR ANY AFFILIATE PROVIDES ANY WARRANTIES OF ANY KIND
        REGARDING ANY USER’S POSTING, COMMENT, PICTURE, OR ANY OTHER INFORMATION
        POSTED ON THE SITE BY ANY USER. WE ARE NOT LIABLE FOR ANY INFORMATION OR
        CONTENT POSTED ON THE SITE OR FOR ANY LOSSES OR DAMAGES, INCLUDING, BUT
        NOT LIMITED TO, ANY INDIRECT, CONSEQUENTIAL, SPECIAL, INCIDENTAL OR
        PUNITIVE DAMAGES, OR LOST PROFITS OR LOSS OF GOODWILL THAT RESULT FROM
        ANY COMMUNICATIONS OR DISCLOSURE OF ANY USER GENERATED CONTENT ON THE
        SITE. YOU UNDERSTAND THAT BY USING THE SITE, YOU MAY BE EXPOSED TO
        CONTENT THAT IS OFFENSIVE, INDECENT OR OBJECTIONABLE AND THAT, IN THIS
        RESPECT, YOU USE THE SITE AT YOUR OWN RISK.
        <br />
        <br />
        WE RESERVE THE RIGHT TO MONITOR ALL POSTINGS TO THE SITE AND MAY DELETE
        OR MODIFY ANY POSTINGS THAT VIOLATE THESE TERMS OF SERVICE OR ARE
        OTHERWISE DEEMED TO BE OBJECTIONABLE AS WE MAY DETERMINE AT OUR SOLE
        DISCRETION. ANY MESSAGES, ADVICE, OPINIONS, OR OTHER INFORMATION
        CONTAINED IN ANY DISCUSSION AREA SHOULD NOT BE CONSTRUED AS PROFESSIONAL
        ADVICE OR INSTRUCTION.
        <br />
        <br />
        REGISTRATION TO ACCESS CERTAIN FEATURES OF THE SITE, WE MAY ASK YOU TO
        PROVIDE CERTAIN DEMOGRAPHIC INFORMATION INCLUDING GENDER, YEAR OF BIRTH,
        POSTAL CODE, COUNTRY, AND HOUSEHOLD INCOME. IN ADDITION, IF YOU ELECT TO
        SIGN-UP FOR A PARTICULAR FEATURE OF THE SITE, SUCH AS CHAT ROOMS,
        WEBLOGS, OR BULLETIN BOARDS, YOU MAY ALSO BE ASKED TO REGISTER WITH US
        ON THE FORM PROVIDED AND SUCH REGISTRATION MAY REQUIRE YOU TO PROVIDE
        PERSONALLY IDENTIFIABLE INFORMATION SUCH AS YOUR NAME AND EMAIL ADDRESS.
        YOU AGREE TO PROVIDE TRUE, ACCURATE, CURRENT, AND COMPLETE INFORMATION
        ABOUT YOURSELF AS PROMPTED BY THE SITE’S REGISTRATION FORM, AND TO
        MAINTAIN AND PROMPTLY UPDATE THE INFORMATION YOU PROVIDE TO KEEP IT
        TRUE, ACCURATE, CURRENT, AND COMPLETE. IF WE HAVE REASONABLE GROUNDS TO
        SUSPECT THAT SUCH INFORMATION IS UNTRUE, INACCURATE, OR INCOMPLETE, WE
        HAVE THE RIGHT TO SUSPEND OR TERMINATE YOUR ACCOUNT AND REFUSE ANY AND
        ALL CURRENT OR FUTURE USE OF THE SITE (OR ANY PORTION THEREOF). OUR USE
        OF ANY PERSONALLY IDENTIFIABLE INFORMATION YOU PROVIDE TO US AS PART OF
        THE REGISTRATION PROCESS IS GOVERNED BY THE TERMS OF OUR PRIVACY POLICY.
        <br />
        <br />
        PASSWORDS TO USE CERTAIN FEATURES OF THE SITE, YOU MAY NEED A USERNAME
        AND PASSWORD, WHICH YOU WILL RECEIVE THROUGH THE SITE’S REGISTRATION
        PROCESS. YOU ARE RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF THE
        PASSWORD AND ACCOUNT, AND YOU ARE RESPONSIBLE FOR ALL ACTIVITIES
        (WHETHER BY YOU OR BY OTHERS) THAT OCCUR UNDER YOUR PASSWORD OR ACCOUNT.
        YOU AGREE TO NOTIFY US IMMEDIATELY OF ANY UNAUTHORIZED USE OF YOUR
        PASSWORD OR ACCOUNT OR ANY OTHER BREACH OF SECURITY, AND TO ENSURE THAT
        YOU EXIT FROM YOUR ACCOUNT AT THE END OF EACH SESSION. WE CANNOT AND
        WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE ARISING FROM YOUR FAILURE TO
        PROTECT YOUR PASSWORD OR ACCOUNT INFORMATION.
        <br />
        <br />
        LIMITATION OF LIABILITY UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT
        LIMITED TO, NEGLIGENCE, SHALL WE, OUR SUBSIDIARIES AND PARENT COMPANIES
        OR AFFILIATES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR
        CONSEQUENTIAL DAMAGES THAT RESULT FROM THE USE OF, OR THE INABILITY TO
        USE, THE SITE, INCLUDING OUR MESSAGING, BLOGS, COMMENTS OF OTHERS,
        BOOKS, EMAILS, PRODUCTS, OR SERVICES, OR THIRD-PARTY MATERIALS,
        PRODUCTS, OR SERVICES MADE AVAILABLE THROUGH THE SITE OR BY US IN ANY
        WAY, EVEN IF WE ARE ADVISED BEFOREHAND OF THE POSSIBILITY OF SUCH
        DAMAGES. (BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION
        OF CERTAIN CATEGORIES OF DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO
        YOU. IN SUCH STATES, OUR LIABILITY AND THE LIABILITY OF OUR SUBSIDIARIES
        AND PARENT COMPANIES OR AFFILIATES IS LIMITED TO THE FULLEST EXTENT
        PERMITTED BY SUCH STATE LAW.) YOU SPECIFICALLY ACKNOWLEDGE AND AGREE
        THAT WE ARE NOT LIABLE FOR ANY DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT
        OF ANY USER. IF YOU ARE DISSATISFIED WITH THE SITE, ANY MATERIALS,
        PRODUCTS, OR SERVICES ON THE SITE, OR WITH ANY OF THE SITE’S TERMS AND
        CONDITIONS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE
        SITE AND THE PRODUCTS, SERVICES, AND/OR MATERIALS.
        <br />
        <br />
        TERMINATION WE MAY CANCEL OR TERMINATE YOUR RIGHT TO USE THE SITE OR ANY
        PART OF THE SITE AT ANY TIME WITHOUT NOTICE. IN THE EVENT OF
        CANCELLATION OR TERMINATION, YOU ARE NO LONGER AUTHORIZED TO ACCESS THE
        PART OF THE SITE AFFECTED BY SUCH CANCELLATION OR TERMINATION. THE
        RESTRICTIONS IMPOSED ON YOU WITH RESPECT TO MATERIAL DOWNLOADED FROM THE
        SITE, AND THE DISCLAIMERS AND LIMITATIONS OF LIABILITIES SET FORTH IN
        THESE TERMS OF SERVICE, SHALL SURVIVE.
        <br />
        <br />
        OTHER THIS AGREEMENT CONSTITUTES THE ENTIRE AGREEMENT BETWEEN YOU AND
        COMPANY AND SUPERSEDES ANY PRIOR OR CONTEMPORANEOUS AGREEMENTS,
        REPRESENTATIONS, WARRANTIES, AND UNDERSTANDINGS WITH RESPECT TO THE
        SITE, THE CONTENT, AND SERVICES PROVIDED BY OR THROUGH THE SITE, AND THE
        SUBJECT MATTER OF THIS AGREEMENT. TO THE EXTENT THAT ANYTHING IN OR
        ASSOCIATED WITH THE SITE IS IN CONFLICT OR INCONSISTENT WITH THIS
        AGREEMENT, THIS AGREEMENT SHALL TAKE PRECEDENCE. OUR FAILURE TO ENFORCE
        ANY PROVISION OF THIS AGREEMENT SHALL NOT BE DEEMED A WAIVER OF SUCH
        PROVISION NOR OF THE RIGHT TO ENFORCE SUCH PROVISION. IF ANY PROVISION
        OF THIS AGREEMENT SHALL BE DEEMED UNLAWFUL, VOID, OR FOR ANY REASON
        UNENFORCEABLE, THEN THAT PROVISION SHALL BE DEEMED SEVERABLE FROM THIS
        AGREEMENT AND SHALL NOT AFFECT THE VALIDITY AND ENFORCEABILITY OF ANY
        REMAINING PROVISIONS.
      </p>
    </div>
  );
};

export default TermsAndCondition;
